name: Deploy to edwinjr.com
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pygbag
        run: pip install pygbag

      - name: Build game
        run: pygbag --build main.py

      - name: Sync Files to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/web/
          server-dir: /flappymc/
          port: 2222
          protocol: ftps